import re

# should chinese punctuation be spaced?
punctuation_string = "?!.\u060c\u061F"
quoted_pattern_maybe_space = re.compile(r'\"\s?([^"]*?)\s?\"')
english_regex = re.compile(r"([a-zA-Z\-][a-zA-Z_\-'s\.:]*[_0-9]?||\b[a-z0-9]*\b|\d+|'s)")
english_person_names = re.compile(r"\b(\w+\s\w(?!\s\.))\b")

quoted_pattern_no_space = re.compile(r'\"([^"]*?)\"')
quoted_pattern_with_space = re.compile(r'\"\s([^"]*?)\s\"')
quoted_number_pattern = re.compile(r'\"\s(\d{1,2})\s\"')
duration_date_time_number_pattern = re.compile(r'(DURATION_\d|DATE_\d|TIME_\d|NUMBER_\d)', re.IGNORECASE)
# duration_or_date_pattern_lowercase = re.compile(r'duration_\d|date_\d')
multiple_space_pattern = re.compile(r'\s{2,}')

entity_pattern = re.compile(r'([A-Z][A-Z_]*_[0-9]+|GENERIC_ENTITY_[a-zA-Z\.:\d]+)')
only_generic_entity_pattern = re.compile(r'(GENERIC_ENTITY_[a-zA-Z\.:\d]+)')
id_number_pattern = re.compile(r'([0-9]+)')
number_pattern = re.compile(r'\b([0-9]+)\b')
small_number_pattern = re.compile(r'\b([0-9])\b')

quoted_pattern_maybe_space_or_number = re.compile(r'\"\s?([^"]*?)\s?\"|(?<!\[\s)([0-9]+)')


MULTIWOZ_DOMAINS = {
    'en': ('attraction', 'bus', 'hospital', 'hotel', 'restaurant', 'taxi', 'train'),
    'fa': ("جاذبه", "اتوبوس", "بیمارستان", "هتل", "رستوران", "تاکسی", "قطار"),
    'zh': ("景点", "公共汽车", "医院", "旅馆", "餐厅", "出租车", "列车"),
    'it': ("attrazione", "bus", "ospedale", "hotel", "ristorante", "taxi", "treno"),
}

MULTIWOZ_SLOTS = {
    'en': ('area', 'arrive by', 'book day', 'book people', 'book stay', 'book time', 'day', 'department', 'departure',
           'destination', 'food', 'internet', 'leave at', 'leaveAt', 'name', 'parking', 'price range', 'stars', 'type'),
    'fa': (
        "منطقه", "رسیدن تا", "رزرو روز", "رزرو مردم", "رزرو اقامت", "رزرو زمان", "روز", "بخش", "عزیمت", "مقصد", "غذا",
        "اینترنت", "زمان ترک", "زمان ترک", "نام", "پارکینگ", "محدوده قیمت", "ستاره", "نوع"),
    'zh': (
        '区域', '到达时间', '预订日期', '预订人数', '预订停留天数', '预订时间', '日期', '科室', '出发地', '目的地', '食物', '互联网', '出发时间', '出发时间', '名称',
        '停车处',
        '价格范围', '星级', '类型'),
    'it': ("area", "arrivo entro", "prenota giorno", "prenota persone", "prenota soggiorno", "ora prenota", "giorno",
           "reparto", "partenza", "destinazione", "cibo", "internet", "leave at", "leaveAt", "name", "parking",
           "price range", "stars", "type")
}

RISAWOZ_DOMAINS = {
    'en': ('Tourist attractions', 'restaurants', 'hotels', 'computers', 'trains', 'airplanes', 'weather', 'movies',
           'TV series', 'tutorial classes', 'cars', 'hospitals'),
    'zh': ('旅游景点', '餐厅', '酒店', '电脑', '火车', '飞机', '天气', '电影', '电视剧', '辅导班', '汽车', '医院'),
    'fa': ("جاذبه های گردشگری", "رستوران", "هتل", "رایانه", "قطار", "هواپیما", "هوا", "فیلم", "مجموعه های تلویزیونی",
           "کلاس های آموزشی", "اتومبیل", "بیمارستان"),
    'uk': ("Туристичні визначні пам'ятки", 'ресторани', 'готелі', "комп'ютери", 'поїзди', 'літаки', 'погода', 'фільми',
           'серіали', 'підручники', 'машини', 'лікарні'),
    'sv': ('Turistattraktioner', 'restauranger', 'hotell', 'datorer', 'tåg', 'flygplan', 'väder', 'filmer', 'TV-serier',
           'handledningskurser', 'bilar', 'sjukhus'),
    'fi': (
        "Matkailukohteet", "ravintolat", "hotellit", "tietokoneet", "junat", "lentokoneet", "sää", "elokuvat",
        "TV-sarjat",
        "oppitunnit", "autot", "sairaalat"),
    'de': ("Touristenattraktionen", "Restaurants", "Hotels", "Computer", "Züge", "Flugzeuge", "Wetter", "Filme",
           "Fernsehserien", "Übungsklassen", "Autos", "Krankenhäuser")
}

RISAWOZ_SLOTS = {
    'en': ('Name', 'Area', 'Type of attraction', 'Best for the crowd', 'Consumption',
           'Whether the subway is directly accessible', 'Ticket price', 'Phone number', 'Address',
           'Score', 'Open Time',
           'Features', 'Name', 'Area', 'Cuisine', 'Price', 'Whether the subway is directly accessible',
           'Per capita consumption', 'Address', 'Phone number', 'Score', 'Business hours',
           'Recommended dishes',
           'Name', 'Area', 'Star rating', 'Price range', 'Hotel type', 'Room type', 'Parking lot',
           'Room rate',
           'Address', 'Phone number', 'rating', 'brand', 'product category', 'category',
           'memory capacity',
           'screen size', 'CPU', 'price range', 'series', 'product name', 'system', 'Game performance',
           'CPU model',
           'bare metal weight', 'graphics card category', 'graphics card model', 'features',
           'color series',
           'standby time', 'hard disk capacity', 'price', 'Departure Place', 'Destination', 'Date',
           'Model', 'Seat',
           'Train Information', 'Duration', 'Departure Time', 'Arrival Time', 'Fare', 'Departure Place',
           'Destination',
           'Date', 'Class of Class', 'Flight Information', 'Departure Time', 'Arrival Time', 'Fare',
           'Punctuality',
           'City', 'Date', 'Weather', 'Temperature', 'Wind wind direction', 'Ultraviolet intensity',
           'Production country/region', 'Type', 'Year', 'Starring', 'Director', 'Title',
           'List of leading actors',
           'Specific release time', 'length', 'douban rating', 'production country/region', 'genre',
           'year', 'leader',
           'director', 'title', 'list of lead actors', 'First broadcast time', 'episode number',
           'single episode length', 'douban score', 'class number', 'difficulty', 'subject', 'grade',
           'area', 'campus',
           'teaching method', 'Start date', 'End date', 'Weekly', 'Class time', 'Class time',
           'Time period',
           'Class number', 'Class hour', 'Classroom location', 'Teacher', 'Price', 'Course URL',
           'Teacher\'s URL',
           'Name', 'Model', 'Level', 'Number of Seats', 'Body Size (mm)', 'Manufacturer', 'Energy Type',
           'Engine Displacement (L)', 'Engine horsepower (Ps)', 'Driving mode',
           'Comprehensive fuel consumption (L/100km)', 'Environmental protection standard',
           'Drive assist image',
           'Cruise system', 'Price (ten thousand yuan)', 'Car series', 'Power level',
           'Fuel consumption level',
           'reversing image', 'fixed speed cruise', 'seat heating', 'seat ventilation',
           'belonging to price range',
           'name', 'grade', 'category', 'nature', 'area', 'Address', 'Telephone', 'Registration time',
           'Outpatient time', 'Bus line', 'Metro reachable', 'Metro line', 'Key department', 'CT',
           '3.0T MRI', 'DSA'),
    'zh': (
        '名称', '区域', '景点类型', '最适合人群', '消费', '是否地铁直达', '门票价格', '电话号码', '地址', '评分', '开放时间', '特点', '名称',
        '区域', '菜系', '价位',
        '是否地铁直达', '人均消费', '地址', '电话号码', '评分', '营业时间', '推荐菜', '名称', '区域', '星级', '价位', '酒店类型', '房型',
        '停车场', '房费', '地址',
        '电话号码', '评分', '品牌', '产品类别', '分类', '内存容量', '屏幕尺寸', 'CPU', '价格区间', '系列', '商品名称', '系统', '游戏性能',
        'CPU型号', '裸机重量',
        '显卡类别', '显卡型号', '特性', '色系', '待机时长', '硬盘容量', '价格', '出发地', '目的地', '日期', '车型', '坐席', '车次信息', '时长',
        '出发时间', '到达时间',
        '票价', '出发地', '目的地', '日期', '舱位档次', '航班信息', '起飞时间', '到达时间', '票价', '准点率', '城市', '日期', '天气', '温度',
        '风力风向', '紫外线强度',
        '制片国家/地区', '类型', '年代', '主演', '导演', '片名', '主演名单', '具体上映时间', '片长', '豆瓣评分', '制片国家/地区', '类型', '年代',
        '主演', '导演',
        '片名',
        '主演名单', '首播时间', '集数', '单集片长', '豆瓣评分', '班号', '难度', '科目', '年级', '区域', '校区', '上课方式', '开始日期',
        '结束日期', '每周', '上课时间',
        '下课时间', '时段', '课次', '课时', '教室地点', '教师', '价格', '课程网址', '教师网址', '名称', '车型', '级别', '座位数',
        '车身尺寸(mm)', '厂商', '能源类型',
        '发动机排量(L)', '发动机马力(Ps)', '驱动方式', '综合油耗(L/100km)', '环保标准', '驾驶辅助影像', '巡航系统', '价格(万元)', '车系',
        '动力水平', '油耗水平',
        '倒车影像',
        '定速巡航', '座椅加热', '座椅通风', '所属价格区间', '名称', '等级', '类别', '性质', '区域', '地址', '电话', '挂号时间', '门诊时间',
        '公交线路', '地铁可达',
        '地铁线路',
        '重点科室', 'CT', '3.0T MRI', 'DSA'),
    'fa': ("نام", "منطقه", "نوع جاذبه", "بهترین حالت برای جمعیت", "مصرف", "آیا دسترسی مستقیم به مترو",
           "قیمت بلیط",
           "شماره تلفن", "آدرس", "امتیاز", "ساعات کاری ", "ویژگی ها", "نام", "منطقه", "آشپزی", "قیمت",
           "آیا مترو مستقیماً قابل دسترسی است", "مصرف سرانه", "آدرس", "شماره تلفن", "امتیاز",
           "ساعات کاری",
           "غذاهای توصیه شده", "نام", "منطقه", "ستاره", 'قیمت', 'نوع هتل', 'نوع اتاق', 'پارکینگ',
           'نرخ اتاق', 'آدرس',
           "شماره تلفن", "امتیاز", "مارک", "گروه محصول", "طبقه بندی", "ظرفیت حافظه", "اندازه صفحه",
           "پردازنده",
           "محدوده قیمت", "سری", "نام محصول", "سیستم", "عملکرد بازی", "مدل CPU", "وزن فلز برهنه",
           "نوع کارت گرافیک", "مدل کارت گرافیک", "ویژگی ها", "سری رنگ", "زمان آماده به کار",
           "ظرفیت دیسک سخت", "قیمت",
           "عزیمت", "مقصد", "تاریخ", "مدل", "صندلی ", "اطلاعات قطار", "مدت زمان", "زمان عزیمت",
           "زمان ورود",
           "کرایه", "محل عزیمت", "مقصد", "تاریخ", "کلاس کلاس", "اطلاعات پرواز", "زمان عزیمت",
           "زمان ورود", "کرایه",
           "زمان دقت", "شهر", "تاریخ", "هوا", "دما", "جهت باد", "شدت فرابنفش",
           "کشور / منطقه تولید", "ژانر", "سال", "رهبر", "کارگردان", "عنوان", "لیست رهبران",
           "زمان اکران خاص", "طول",
           "رتبه بندی دوبان", "کشور تولید /منطقه ", "ژانر", "سال", "با بازی", "کارگردان",
           'عنوان',
           "لیست بازیگران برجسته", "زمان پخش اول", "تعداد قسمت ها", "طول قسمت تنها", "نمره دوبان",
           "شماره کلاس",
           "دشواری", "موضوع", "درجه", "منطقه", "پردیس", "روش کلاس", "تاریخ شروع", "تاریخ پایان",
           "هفتگی", "زمان کلاس",
           "زمان کلاس", "دوره زمانی", "اوقات کلاس", "ساعت کلاس", "مکان کلاس", "معلم", "قیمت",
           "URL دوره", "URL معلم",
           "نام", "مدل", "سطح", "تعداد صندلی ها", "اندازه بدنه (میلی متر)", "تولید کننده", "نوع انرژی",
           "جابجایی موتور (L)", "اسب بخار موتور (PS)", "حالت رانندگی",
           "مصرف سوخت جامع (L / 100 کیلومتر)",
           "استانداردهای زیست محیطی", "تصویر کمک رانندگی", "سیستم کروز", "قیمت (ده هزار یوان) ",
           "سری ماشین",
           "سطح قدرت ", "سطح مصرف سوخت",
           "عکس معکوس",
           "سرعت کروز", "گرم شدن صندلی", "تهویه صندلی", "محدوده قیمت", "نام", "درجه", "دسته", "طبیعت",
           "منطقه", "آدرس",
           "تلفن", "زمان ثبت نام", "سرپایی ", "خط اتوبوس", "مترو قابل دسترسی",
           "خط مترو",
           "بخشهای کلیدی", "CT", "3.0T MRI", "DSA"),
    'uk': (
        "Ім'я", "Площа", "Тип атракціону", "Найкраще для натовпу", "Споживання",
        "Чи є метро безпосередньо доступним",
        "Ціна квитка", "Номер телефону", "Адреса", "Оцінка", 'Години роботи', 'особливості', 'назва',
        'площа',
        'кухня', 'ціна',
        "Чи є метро безпосередньо доступним", "Споживання на душу населення", "Адреса",
        "Номер телефону", "Оцінка",
        "Робочий час", "Рекомендовані страви", "Ім'я", "Площа", "Зірка", 'Ціна', 'Тип готелю',
        'Тип номера', 'Стоянка',
        'Оплата за номер', 'Адреса',
        'Номер телефону', 'Оцінка', 'Бренд', 'Категорія товару', 'Класифікація', "Об'єм пам'яті",
        'Розмір екрана',
        'Процесор', 'Діапазон цін', 'Серія', 'Назва товару', 'Система', 'Продуктивність гри',
        'Модель процесора',
        'гола металева вага',
        'Тип графічної картки', 'модель графічної карти', 'особливості', 'кольорова серія',
        'час очікування',
        'ємність жорсткого диска', 'ціна', 'відправлення', 'призначення', 'дата', 'модель', 'Місце',
        'Інформація про подорож', 'Тривалість', 'Час вильоту', 'Час прибуття',
        'Вартість проїзду', 'Місце вильоту', 'Пункт призначення', 'Дата', 'Клас класу',
        'Інформація про рейс',
        'Час вильоту', 'Час прибуття', 'Вартість проїзду', 'Рівень пунктуальності', 'Місто', 'Дата',
        'Погода',
        'Температура', 'Напрямок вітру', 'Інтенсивність ультрафіолету',
        'Країна / регіон виробництва', 'жанр', 'рік', 'лідер', 'режисер', 'назва',
        'список провідних акторів',
        'конкретний час випуску', 'тривалість', 'рейтинг дубана',
        'Країна / регіон виробництва', "жанр", "рік", "головна роль", "режисер",
        'Назва', 'Список провідних акторів', 'Час першого ефіру', 'Кількість серій',
        'Тривалість одного епізоду',
        'Бал Дубана', 'Номер класу', 'Складність', 'Тема', 'Оцінка', 'Регіон', "Кампус", "Метод занять",
        "Дата початку",
        "Дата закінчення", "Щотижня", "Час заняття",
        'Час занять', 'Час доби', 'Час занять', 'Години занять', 'Розташування класу', 'Вчитель',
        'Ціна',
        'URL-адреса курсу', 'URL-адреса викладача', "Ім'я", 'Модель', 'Рівень', 'Кількість місць',
        'Розмір кузова (мм)', 'Виробник', 'Тип енергії',
        "Робочий об'єм двигуна (L)", 'Потужність двигуна (Ps)', 'Режим руху',
        'Комплексне споживання палива (L / 100км)',
        'Екологічні норми', 'Зображення допомоги при водінні', 'Круїзна система',
        'Ціна (Десять тисяч юанів)',
        'автомобільна система', 'рівень потужності', 'рівень споживання палива',
        'Зворотне зображення',
        'Круїзний круїз', 'обігрів сидінь', 'вентиляція сидінь', 'діапазон цін', 'назва', 'сорт',
        'категорія',
        'природа',
        'зона', 'адреса', 'телефон', 'Реєстрація час', 'Час амбулаторного лікування', 'Автобусна лінія',
        'Доїзд до метро',
        'Лінія метро',
        'Ключові відділи', 'КТ', '3,0 Т МРТ', 'DSA'),
    'sv': ('Namn', 'Område', 'Typ av attraktion', 'Bäst för publiken', 'Förbrukning',
           'Huruvida tunnelbanan är direkt tillgänglig', 'Biljettpris', 'Telefonnummer', 'Adress',
           'Poäng',
           'Öppettider', 'funktioner', 'namn', 'område', 'kök', 'pris',
           'Om tunnelbanan är direkt tillgänglig', 'Per capita-förbrukning', 'Adress', 'Telefonnummer',
           'Poäng',
           'Öppettider', 'Rekommenderade rätter', 'Namn', 'Område', 'Stjärna', 'Pris', 'Hotelltyp',
           'rumstyp',
           'parkeringsplats', 'rumsavgift', 'adress',
           'Telefonnummer', 'Poäng', 'Märke', 'Produktkategori', 'Klassificering', 'Minneskapacitet',
           'Skärmstorlek',
           'CPU', 'Prisklass', 'Serie', 'Produktnamn', 'System', 'Spelprestanda', 'CPU-modell',
           'bare metallvikt',
           'Grafikkorttyp', 'grafikkortmodell', 'funktioner', 'färgserie', 'standbytid',
           'hårddiskkapacitet', 'pris',
           'avgång', 'destination', 'datum', 'modell', 'Sittplats', 'Reseinformation', 'Varaktighet',
           'Avgångstid', 'Ankomsttid',
           'Pris', 'Avgångsställe', 'Destination', 'Datum', 'Klass av klass', 'Flyginformation',
           'Avgångstid',
           'Ankomsttid', 'Pris', 'Punktlighet', 'Stad', 'Date', 'Weather', 'Temperature',
           'Wind Direction',
           'Ultraviolet Intensity',
           'Produktionsland / region', 'genre', 'år', 'ledare', 'regissör', 'titel',
           'lista över ledande skådespelare',
           'specifik släpptid', 'längd', 'douban-betyg', 'Produktionsland / region', 'genre', 'år',
           'medverkande', 'regissör',
           'Titel', 'Lista över ledande skådespelare', 'Första sändningstid', 'Antal avsnitt',
           'Längd för enstaka avsnitt', 'Douban-poäng', 'Klassnummer', 'Svårighetsgrad', 'Ämne',
           'Betyg', 'Region',
           'Campus', 'Klassmetod', 'Startdatum', 'Slutdatum', 'Veckovis', 'Klasstid',
           'Klass tid', 'Tid på dagen', 'Klass gånger', 'Klass timmar', 'Klassrumsplats', 'Lärare',
           'Pris', 'Kurs-URL',
           'Lärar-URL', 'Namn', 'Modell', 'Nivå', 'Antal sittplatser', 'Kroppsstorlek (mm)',
           'Tillverkare',
           'Energityp',
           'Motorvolym (L)', 'Motorhästkrafter (Ps)', 'Körläge',
           'Omfattande bränsleförbrukning (L / 100 km)',
           'Miljöstandarder', 'Körassistansbild', 'Kryssningssystem', 'Pris (Tiotusen yuan)',
           'bilsystem',
           'effektnivå', 'bränsleförbrukningsnivå',
           'Omvänd bild',
           'Kryssningskryssning', 'sätesuppvärmning', 'sätesventilation', 'prisklass', 'namn', 'klass',
           'kategori',
           'natur', 'område', 'adress', 'telefon', 'registrering tid', 'Poliklinisk tid', 'Busslinje',
           'Tunnelbana kan nås',
           'Subway Line',
           'Key Departments', 'CT', '3.0T MRI', 'DSA'),
    'fi': ('Nimi', 'Alue', 'Nähtävyystyyppi', 'Yleisölle parhaiten sopiva', 'Kulutus',
           'Onko metroon pääsee suoraan',
           'Lippujen hinta', 'Puhelinnumero', 'Osoite', 'Pisteet', 'Aukioloajat', 'ominaisuudet',
           'nimi',
           'alue', 'keittiö', 'hinta',
           'Pääsy metroon suoraan', 'Kulutus asukasta kohti', 'Osoite', 'Puhelinnumero', 'Pisteet',
           'Työajat', 'Suositellut ruokalajit', 'Nimi', 'Alue', 'Tähti', 'Hinta', 'Hotellityyppi',
           'Huonetyyppi', 'Pysäköintialue', 'Huonehinta', 'Osoite',
           'Puhelinnumero', 'Pisteet', 'Tuotemerkki', 'Tuoteryhmä', 'Luokittelu', 'Muistikapasiteetti',
           'Näytön koko',
           'Keskusyksikkö', 'Hintaluokka', 'Sarja', 'Tuotteen nimi', 'Järjestelmä',
           'Pelin suorituskyky',
           'Suorittimen malli', 'paljaan metallin paino',
           'Grafiikkakortin tyyppi', 'Graafisen kortin malli', 'Ominaisuudet', 'Värisarja',
           'Valmiustila',
           'Kiintolevyn kapasiteetti', 'Hinta', 'Lähtö', 'Kohde', 'Päivämäärä', 'malli', 'Istuin',
           'matkatiedot', 'kesto', 'lähtöaika', 'saapumisaika',
           'Hinta', 'Lähtöpaikka', 'Kohde', 'Päivämäärä', 'Luokan luokka', 'Lentotiedot', 'Lähtöaika',
           'Saapumisaika',
           'Hinta', 'täsmällisyysaste', 'kaupunki', 'Päivämäärä', 'Sää', 'Lämpötila', 'Tuulen suunta',
           'Ultravioletti-intensiteetti',
           'Tuotantimaa / -alue', 'genre', 'vuosi', 'johtaja', 'ohjaaja', 'otsikko',
           'luettelo johtavista toimijoista',
           'tietty julkaisuaika', 'pituus', 'douban-luokitus', 'Tuotantomaa / -alue', 'genre', 'vuosi',
           'pääosissa', 'ohjaaja',
           'Otsikko', 'Luettelo johtavista toimijoista', 'Ensimmäinen lähetysaika', 'Jaksoiden määrä',
           'Yhden jakson pituus', 'Douban-pisteet', 'Luokan numero', 'Vaikeus', 'Aihe', 'Arvosana',
           'Alue', 'Kampus',
           'Luokan menetelmä', 'Aloituspäivä', 'Lopetuspäivä', 'Viikoittain', 'Luokan aika',
           'Kurssin aika', 'Aikajakso', 'Kurssin ajat', 'Kurssitunnit', 'Luokan sijainti', 'Opettaja',
           'Hinta',
           'Kurssin URL', 'Opettajan URL', 'Nimi', 'Malli', 'Taso', 'Istuinten lukumäärä',
           'Rungon koko (mm)',
           'Valmistaja', 'Energiatyyppi',
           'Moottorin iskutilavuus (L)', 'Moottorin hevosvoima (Ps)', 'Ajotila',
           'Kattava polttoaineenkulutus (L / 100km)', 'Ympäristötandardit', 'Ajoapukuva',
           'Risteilyjärjestelmä',
           'Hinta (Kymmenentuhatta yuania)', 'autojärjestelmä', 'tehotaso', 'polttoaineenkulutustaso',
           'Käänteinen kuva',
           'Risteilyristeily', 'istuimenlämmitys', 'istuimen tuuletus', 'hintaluokka', 'nimi', 'luokka',
           'luokka',
           'luonto', 'alue', 'osoite', 'puhelin', 'rekisteröinti aika', 'Avohoidon aika', 'Linja-auto',
           'Metro saavutettavissa',
           'Metrolinja',
           'Keskeiset osastot', 'CT', '3.0T MRI', 'DSA'),
    'de': ('Name', 'Gebiet', 'Art der Attraktion', 'Best for the Crowd', 'Consumption',
           "Ob die U-Bahn direkt erreichbar ist", "Ticketpreis", "Telefonnummer", "Adresse",
           'Score', 'Open Time',
           'Features', 'Name', 'Area', 'Cuisine', 'Price', 'Ob die U-Bahn direkt erreichbar ist',
           "Pro-Kopf-Verbrauch", "Adresse", "Telefonnummer", "Punktzahl", "Geschäftszeiten",
           "Empfohlene Gerichte",
           'Name', 'Fläche', 'Sternebewertung', 'Preisspanne', 'Hoteltyp', 'Zimmertyp', 'Parkplatz',
           'Zimmerpreis',
           'Adresse', 'Telefonnummer', 'Bewertung', 'Marke', 'Produktkategorie', 'Kategorie',
           'Speicherkapazität',
           'Bildschirmgröße', 'CPU', 'Preisspanne', 'Serie', 'Produktname', 'System', 'Spieleleistung',
           'CPU-Modell',
           "Bare-Metal-Gewicht", "Grafikkartenkategorie", "Grafikkartenmodell", "Funktionen",
           'Farbserie',
           'Standby-Zeit', 'Festplattenkapazität', 'Preis', 'Abflugort', 'Ziel', 'Datum',
           "Modell", "Sitz",
           'Zuginformationen', 'Dauer', 'Abfahrtszeit', 'Ankunftszeit', 'Fahrpreis', 'Abfahrtsort',
           'Ziel',
           'Datum', 'Klassenklasse', 'Fluginformationen', 'Abflugzeit', 'Ankunftszeit', 'Tarif',
           'Pünktlichkeit', "Stadt", "Datum", "Wetter", "Temperatur", "Windwindrichtung", "UV-Intensität",
           'Produktionsland / Region', 'Typ', 'Jahr', 'Darsteller', 'Regisseur', 'Titel',
           'Liste der Hauptdarsteller',
           "Spezifische Veröffentlichungszeit", "Länge", "Douban-Bewertung", "Produktionsland / -region", "Genre",
           'Jahr', 'Führer',
           "Regisseur", "Titel", "Liste der Hauptdarsteller", "Erste Sendezeit", "Episodennummer",
           'Länge einer einzelnen Episode', 'Douban Score', 'Klassennummer', 'Schwierigkeitsgrad', 'Fach', 'Klasse',
           "Bereich", "Campus",
           'Unterrichtsmethode', 'Startdatum', 'Enddatum', 'Wöchentlich', 'Unterrichtszeit', 'Unterrichtszeit',
           'Zeitraum',
           'Klassennummer', 'Unterrichtsstunde', 'Unterrichtsort', 'Lehrer', 'Preis', 'Kurs-URL',
           'URL des Lehrers',
           'Name', 'Modell', 'Stufe', 'Anzahl der Sitze', 'Körpergröße (mm)', 'Hersteller', 'Energietyp',
           'Hubraum (L)', 'Motorleistung (Ps)', 'Fahrmodus',
           "Umfassender Kraftstoffverbrauch (L / 100 km)", "Umweltschutznorm",
           'Drive Assist Image',
           "Kreuzfahrtsystem", "Preis (zehntausend Yuan)", "Autoserie", "Leistungsstufe",
           'Kraftstoffverbrauchsniveau',
           "Bild umkehren", "Kreuzfahrt mit fester Geschwindigkeit", "Sitzheizung", "Sitzbelüftung",
           "Zugehörigkeit zur Preisspanne",
           'Name', 'Klasse', 'Kategorie', 'Natur', 'Gebiet', 'Adresse', 'Telefon', 'Registrierungszeit',
           "Ambulante Zeit", "Buslinie", "U-Bahn erreichbar", "U-Bahnlinie", "Schlüsselabteilung", "CT",
           "3.0T MRI", "DSA")
}
