SHELL := /bin/bash

-include project.config
-include arguments.config

# order is important (we have multiple targets with same patterns and make chooses the first one that matches)

-include data.mk
-include translate.mk
-include translate_direct.mk




